# -*- coding: utf-8 -*-
"""factorial

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EqqkCd-cjxgowVJYz93XcIfC5EjFSa2B
"""

n=5
fact=1
for i in range(1,6):
  fact=fact*i
print(fact)